CREATE DATABASE CONSOLE
ON PRIMARY (
	NAME='SGMS_DB_Data1',
	FILENAME='C:\db\1\SDMS_DB_Data1.mdf',
	SIZE=10MB,
	MAXSIZE=50MB,
	FILEGROWTH=20%
),

FILEGROUP fgroup(
	NAME='SGMS_DB_Data2',
	FILENAME='C:\db\1\SDMS_DB_Data2.mdf',
	SIZE=10MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%

)

LOG ON (
	NAME='SGMS_DB_log',
	FILENAME='C:\db\1\SDMS_DB_log.lndf',
	SIZE=20MB,
	MAXSIZE=100MB,
	FILEGROWTH=10MB
)
GO